// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Book struct {
	ID     *string `json:"id"`
	Author *string `json:"author"`
	Title  *string `json:"title"`
	Isbn   *string `json:"isbn"`
}

type BookInput struct {
	ID     *string `json:"id"`
	Author *string `json:"author"`
	Title  *string `json:"title"`
	Isbn   *string `json:"isbn"`
}

type HolderInput struct {
	ID        *string `json:"id"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Phone     *string `json:"phone"`
	Email     *string `json:"email"`
}
